name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: NPM CI
      run: npm ci
    - name: build
      run: npm run build
    - name: Cache Node Modules
      uses: actions/cache@v1.0.2
      with:
        # A directory to store and save the cache
        path: node_modules
        # An explicit key for restoring and saving the cache
        key: linked
    - name: ZEIT Now Deployment
      id: "zeit"
      uses: amondnet/now-deployment@v1
      with:
        # zeit.co token
        zeit-token: ${{secrets.ZEIT_TOKEN}}
        now-args: '--prod'
        github-token: ${{secrets.git_token}}
        # if you want to create github deployment, set true, default: false
        githb-deployment: false
    - name: Display preview url
      run: |
        echo "Preview URL:"
        echo ${{steps.4.outputs.preview_url}}
